local harpoon = require("harpoon")
harpoon:setup()
-- harpoon mappings
vim.keymap.set("n", "<leader>aa", function() harpoon:list():append() end)
vim.keymap.set("n", "<C-e>", function() harpoon.ui:toggle_quick_menu(harpoon:list()) end)
vim.keymap.set("n", "<leader>ee", function() harpoon.ui:toggle_quick_menu(harpoon:list()) end)
vim.keymap.set("n", "<leader>hu", function() harpoon:list():select(1) end)
vim.keymap.set("n", "<leader>hi", function() harpoon:list():select(2) end)
vim.keymap.set("n", "<leader>ho", function() harpoon:list():select(3) end)
vim.keymap.set("n", "<leader>hp", function() harpoon:list():select(4) end)
